[build]
  # Install dependencies and bundle application code for the serverless function
  command = "pip install -r netlify/functions/requirements.txt -t netlify/functions && cp -r webapp netlify/functions && pip install -r requirements.txt"
  functions = "netlify/functions"
  publish = "webapp/static"

[dev]
  command = "flask run --port 8888"
  targetPort = 8888
